name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Change this to your default branch name (e.g., 'master') if different

permissions:
  contents: write

jobs:
  deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./src/pages # This will make the contents of src/pages available at the root URL
          force_push: true
